//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// AppMfc.rc에서 사용되고 있습니다.
//
#define IDB_OK                          5
#define IDB_BUZZER_OFF                  6
#define IDD_APPMFC_DIALOG               102
#define IDD_ERROR_MSG                   104
#define IDD_INFO_BOX                    105
#define IDD_GET_NUMBER                  106
#define IDR_MAINFRAME                   128
#define IDD_AUTO_MODE_SELECT            310
#define IDD_GET_VALUE                   315
#define IDD_DATA_SIXBTN                 319
#define IDD_DATA_THREEBTN               321
#define IDD_POP_TASK_ERR_MSG            333
#define IDD_TRANSPARENT_GUIDE_DLG       389
#define IDD_IMGUI_WIND                  391
#define IDD_MSG_BOX1                    392
#define IDD_POP_VIEW_MSG                422
#define IDS_INFO_OBJ_ID                 1000
#define IDC_LIST1                       1005
#define IDC_PAGE_GUIDE_TITLE_1          1006
#define IDC_ERR_MSG_BUZZER_OFF          1011
#define IDC_ERR_MSG_OK                  1014
#define IDC_ERR_MSG_SHOW                1017
#define IDC_ERR_MSG_EDIT_OBJ            1019
#define IDC_ERR_MSG_EDIT_UNIT           1021
#define IDC_ERR_MSG_EDIT_CONTENT        1023
#define IDC_ERR_MSG_EDIT_INFOR          1025
#define IDC_ERR_MSG_STA_INFOR           1026
#define IDC_FRAME_PICTURE               1027
#define IDC_MSG_BOX_YES                 1028
#define IDC_MSG_BOX_OK                  1029
#define IDC_MSG_BOX_CANCEL              1030
#define IDC_MSG_BOX_RETRY               1031
#define IDC_MSG_EDIT_VIEW               1032
#define IDC_MSG_BOX_NO                  1034
#define IDB_PASS_RUN                    1138
#define IDB_REPAIR_RUN                  1143
#define IDB_EXIT                        1356
#define IDC_BUTTON3                     1371
#define IDC_BUTTON4                     1372
#define IDC_BUTTON5                     1373
#define IDC_BUTTON6                     1374
#define IDB_MODE_SELECT_AUTO_RUN        1388
#define IDB_MODE_SELECT_IDLE_RUN        1437
#define IDC_BTN_1                       1443
#define IDB_BTN_MINUS                   1444
#define IDB_BTN_EQUAL                   1445
#define IDC_BTN_2                       1446
#define IDC_BTN_3                       1447
#define IDC_BTN_4                       1448
#define IDC_BTN_7                       1449
#define IDC_BTN_5                       1450
#define IDC_BTN_6                       1451
#define IDC_BTN_8                       1453
#define IDC_BTN_9                       1454
#define IDC_BTN_0                       1455
#define IDB_POP_MODE_SELECT_SAVE        1455
#define IDB_BTN_DOT                     1456
#define IDB_BTN_SIGN                    1457
#define IDB_POP_MODE_SELECT_EXIT        1459
#define IDB_BTN_BACK                    1461
#define IDB_BTN_CLEAR                   1462
#define IDB_BTN_OK                      1463
#define IDB_BTN_ESC                     1464
#define IDB_KEY_8                       1465
#define IDB_KEY_9                       1466
#define IDB_KEY_0                       1467
#define IDB_KEY_EQUAL                   1468
#define IDB_KEY_BACK                    1469
#define IDB_KEY_Q                       1470
#define IDB_KEY_W                       1471
#define IDB_KEY_E                       1472
#define IDB_KEY_R                       1474
#define IDB_KEY_T                       1476
#define IDB_KEY_Y                       1478
#define IDB_KEY_U                       1480
#define IDB_KEY_I                       1482
#define IDB_KEY_O                       1484
#define IDB_KEY_P                       1486
#define IDB_KEY_WON                     1488
#define IDB_KEY_CLEAR                   1490
#define IDB_KEY_A                       1492
#define IDB_KEY_S                       1494
#define IDB_KEY_D                       1496
#define IDB_KEY_F                       1498
#define IDB_KEY_G                       1500
#define IDB_KEY_H                       1502
#define IDB_KEY_J                       1504
#define IDB_KEY_K                       1506
#define IDB_KEY_L                       1508
#define IDB_KEY_COLON                   1510
#define IDB_KEY_OK                      1513
#define IDB_KEY_Z                       1515
#define IDB_KEY_X                       1519
#define IDB_KEY_C                       1521
#define IDB_KEY_V                       1524
#define IDB_KEY_B                       1527
#define IDB_KEY_N                       1530
#define IDB_KEY_M                       1533
#define IDB_KEY_DOT                     1536
#define IDS_MODIFY                      1539
#define IDB_KEY_DASH                    1540
#define IDC_MODIFY                      1543
#define IDB_KEY_UNDER_BAR               1545
#define IDB_KEY_ESC                     1547
#define IDC_DISP_VAL                    1549
#define IDB_KEY_1                       1551
#define IDB_KEY_2                       1553
#define IDB_KEY_3                       1555
#define IDB_KEY_4                       1557
#define IDB_KEY_5                       1559
#define IDB_KEY_6                       1561
#define IDB_KEY_7                       1563
#define IDS_PRESENT                     1565
#define IDC_PRESENT                     1567
#define IDB_BTN_PLUS                    1569
#define IDC_BUTTON1                     1593
#define IDC_PICTURE                     1594
#define IDC_EDITLABEL                   1595
#define IDS_PROCESS_OBJ_ID              1596
#define IDS_UNIT_OBJ_ID                 1597
#define IDS_PROCESS_OBJ_TITLE           1600
#define IDS_UNIT_OBJ_TITLE              1601
#define IDS_ERROR_INFO_TITLE            1602
#define IDS_MESSAGE_TITLE               1603
#define IDB_SYSTEM0                     1606
#define IDS_SYSTEM0                     1607
#define IDC_BUTTON2                     1610
#define IDB_INFO                        1623
#define IDS_MESSAGE                     1716
#define IDS_MESSAGE_ERR_INFO            1717

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
